// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: identity_user.proto

#ifndef PROTOBUF_INCLUDED_identity_5fuser_2eproto
#define PROTOBUF_INCLUDED_identity_5fuser_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_identity_5fuser_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_identity_5fuser_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
class Identity_User;
class Identity_UserDefaultTypeInternal;
extern Identity_UserDefaultTypeInternal _Identity_User_default_instance_;
namespace google {
namespace protobuf {
template<> ::Identity_User* Arena::CreateMaybeMessage<::Identity_User>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class Identity_User :
    public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:Identity_User) */ {
 public:
  Identity_User();
  virtual ~Identity_User();

  Identity_User(const Identity_User& from);

  inline Identity_User& operator=(const Identity_User& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Identity_User(Identity_User&& from) noexcept
    : Identity_User() {
    *this = ::std::move(from);
  }

  inline Identity_User& operator=(Identity_User&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const Identity_User& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Identity_User* internal_default_instance() {
    return reinterpret_cast<const Identity_User*>(
               &_Identity_User_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Identity_User* other);
  friend void swap(Identity_User& a, Identity_User& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Identity_User* New() const final {
    return CreateMaybeMessage<Identity_User>(nullptr);
  }

  Identity_User* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Identity_User>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const Identity_User& from);
  void MergeFrom(const Identity_User& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Identity_User* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // string nickname = 2;
  void clear_nickname();
  static const int kNicknameFieldNumber = 2;
  const ::std::string& nickname() const;
  void set_nickname(const ::std::string& value);
  #if LANG_CXX11
  void set_nickname(::std::string&& value);
  #endif
  void set_nickname(const char* value);
  void set_nickname(const char* value, size_t size);
  ::std::string* mutable_nickname();
  ::std::string* release_nickname();
  void set_allocated_nickname(::std::string* nickname);

  // string head_hash = 3;
  void clear_head_hash();
  static const int kHeadHashFieldNumber = 3;
  const ::std::string& head_hash() const;
  void set_head_hash(const ::std::string& value);
  #if LANG_CXX11
  void set_head_hash(::std::string&& value);
  #endif
  void set_head_hash(const char* value);
  void set_head_hash(const char* value, size_t size);
  ::std::string* mutable_head_hash();
  ::std::string* release_head_hash();
  void set_allocated_head_hash(::std::string* head_hash);

  // string name = 4;
  void clear_name();
  static const int kNameFieldNumber = 4;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // string phone = 6;
  void clear_phone();
  static const int kPhoneFieldNumber = 6;
  const ::std::string& phone() const;
  void set_phone(const ::std::string& value);
  #if LANG_CXX11
  void set_phone(::std::string&& value);
  #endif
  void set_phone(const char* value);
  void set_phone(const char* value, size_t size);
  ::std::string* mutable_phone();
  ::std::string* release_phone();
  void set_allocated_phone(::std::string* phone);

  // string email = 8;
  void clear_email();
  static const int kEmailFieldNumber = 8;
  const ::std::string& email() const;
  void set_email(const ::std::string& value);
  #if LANG_CXX11
  void set_email(::std::string&& value);
  #endif
  void set_email(const char* value);
  void set_email(const char* value, size_t size);
  ::std::string* mutable_email();
  ::std::string* release_email();
  void set_allocated_email(::std::string* email);

  // string home_address = 9;
  void clear_home_address();
  static const int kHomeAddressFieldNumber = 9;
  const ::std::string& home_address() const;
  void set_home_address(const ::std::string& value);
  #if LANG_CXX11
  void set_home_address(::std::string&& value);
  #endif
  void set_home_address(const char* value);
  void set_home_address(const char* value, size_t size);
  ::std::string* mutable_home_address();
  ::std::string* release_home_address();
  void set_allocated_home_address(::std::string* home_address);

  // string born_timestamp = 10;
  void clear_born_timestamp();
  static const int kBornTimestampFieldNumber = 10;
  const ::std::string& born_timestamp() const;
  void set_born_timestamp(const ::std::string& value);
  #if LANG_CXX11
  void set_born_timestamp(::std::string&& value);
  #endif
  void set_born_timestamp(const char* value);
  void set_born_timestamp(const char* value, size_t size);
  ::std::string* mutable_born_timestamp();
  ::std::string* release_born_timestamp();
  void set_allocated_born_timestamp(::std::string* born_timestamp);

  // string idcard = 11;
  void clear_idcard();
  static const int kIdcardFieldNumber = 11;
  const ::std::string& idcard() const;
  void set_idcard(const ::std::string& value);
  #if LANG_CXX11
  void set_idcard(::std::string&& value);
  #endif
  void set_idcard(const char* value);
  void set_idcard(const char* value, size_t size);
  ::std::string* mutable_idcard();
  ::std::string* release_idcard();
  void set_allocated_idcard(::std::string* idcard);

  // string otherid = 12;
  void clear_otherid();
  static const int kOtheridFieldNumber = 12;
  const ::std::string& otherid() const;
  void set_otherid(const ::std::string& value);
  #if LANG_CXX11
  void set_otherid(::std::string&& value);
  #endif
  void set_otherid(const char* value);
  void set_otherid(const char* value, size_t size);
  ::std::string* mutable_otherid();
  ::std::string* release_otherid();
  void set_allocated_otherid(::std::string* otherid);

  // string photo = 13;
  void clear_photo();
  static const int kPhotoFieldNumber = 13;
  const ::std::string& photo() const;
  void set_photo(const ::std::string& value);
  #if LANG_CXX11
  void set_photo(::std::string&& value);
  #endif
  void set_photo(const char* value);
  void set_photo(const char* value, size_t size);
  ::std::string* mutable_photo();
  ::std::string* release_photo();
  void set_allocated_photo(::std::string* photo);

  // string desc = 14;
  void clear_desc();
  static const int kDescFieldNumber = 14;
  const ::std::string& desc() const;
  void set_desc(const ::std::string& value);
  #if LANG_CXX11
  void set_desc(::std::string&& value);
  #endif
  void set_desc(const char* value);
  void set_desc(const char* value, size_t size);
  ::std::string* mutable_desc();
  ::std::string* release_desc();
  void set_allocated_desc(::std::string* desc);

  // string degree = 15;
  void clear_degree();
  static const int kDegreeFieldNumber = 15;
  const ::std::string& degree() const;
  void set_degree(const ::std::string& value);
  #if LANG_CXX11
  void set_degree(::std::string&& value);
  #endif
  void set_degree(const char* value);
  void set_degree(const char* value, size_t size);
  ::std::string* mutable_degree();
  ::std::string* release_degree();
  void set_allocated_degree(::std::string* degree);

  // string job = 16;
  void clear_job();
  static const int kJobFieldNumber = 16;
  const ::std::string& job() const;
  void set_job(const ::std::string& value);
  #if LANG_CXX11
  void set_job(::std::string&& value);
  #endif
  void set_job(const char* value);
  void set_job(const char* value, size_t size);
  ::std::string* mutable_job();
  ::std::string* release_job();
  void set_allocated_job(::std::string* job);

  // string income = 17;
  void clear_income();
  static const int kIncomeFieldNumber = 17;
  const ::std::string& income() const;
  void set_income(const ::std::string& value);
  #if LANG_CXX11
  void set_income(::std::string&& value);
  #endif
  void set_income(const char* value);
  void set_income(const char* value, size_t size);
  ::std::string* mutable_income();
  ::std::string* release_income();
  void set_allocated_income(::std::string* income);

  // string marry = 18;
  void clear_marry();
  static const int kMarryFieldNumber = 18;
  const ::std::string& marry() const;
  void set_marry(const ::std::string& value);
  #if LANG_CXX11
  void set_marry(::std::string&& value);
  #endif
  void set_marry(const char* value);
  void set_marry(const char* value, size_t size);
  ::std::string* mutable_marry();
  ::std::string* release_marry();
  void set_allocated_marry(::std::string* marry);

  // string hobyy = 19;
  void clear_hobyy();
  static const int kHobyyFieldNumber = 19;
  const ::std::string& hobyy() const;
  void set_hobyy(const ::std::string& value);
  #if LANG_CXX11
  void set_hobyy(::std::string&& value);
  #endif
  void set_hobyy(const char* value);
  void set_hobyy(const char* value, size_t size);
  ::std::string* mutable_hobyy();
  ::std::string* release_hobyy();
  void set_allocated_hobyy(::std::string* hobyy);

  // string recommender = 20;
  void clear_recommender();
  static const int kRecommenderFieldNumber = 20;
  const ::std::string& recommender() const;
  void set_recommender(const ::std::string& value);
  #if LANG_CXX11
  void set_recommender(::std::string&& value);
  #endif
  void set_recommender(const char* value);
  void set_recommender(const char* value, size_t size);
  ::std::string* mutable_recommender();
  ::std::string* release_recommender();
  void set_allocated_recommender(::std::string* recommender);

  // string belief = 21;
  void clear_belief();
  static const int kBeliefFieldNumber = 21;
  const ::std::string& belief() const;
  void set_belief(const ::std::string& value);
  #if LANG_CXX11
  void set_belief(::std::string&& value);
  #endif
  void set_belief(const char* value);
  void set_belief(const char* value, size_t size);
  ::std::string* mutable_belief();
  ::std::string* release_belief();
  void set_allocated_belief(::std::string* belief);

  // string idname = 22;
  void clear_idname();
  static const int kIdnameFieldNumber = 22;
  const ::std::string& idname() const;
  void set_idname(const ::std::string& value);
  #if LANG_CXX11
  void set_idname(::std::string&& value);
  #endif
  void set_idname(const char* value);
  void set_idname(const char* value, size_t size);
  ::std::string* mutable_idname();
  ::std::string* release_idname();
  void set_allocated_idname(::std::string* idname);

  // int64 sex = 5;
  void clear_sex();
  static const int kSexFieldNumber = 5;
  ::google::protobuf::int64 sex() const;
  void set_sex(::google::protobuf::int64 value);

  // int64 wechat = 7;
  void clear_wechat();
  static const int kWechatFieldNumber = 7;
  ::google::protobuf::int64 wechat() const;
  void set_wechat(::google::protobuf::int64 value);

  // bool approved = 23;
  void clear_approved();
  static const int kApprovedFieldNumber = 23;
  bool approved() const;
  void set_approved(bool value);

  // @@protoc_insertion_point(class_scope:Identity_User)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::google::protobuf::internal::ArenaStringPtr nickname_;
  ::google::protobuf::internal::ArenaStringPtr head_hash_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr phone_;
  ::google::protobuf::internal::ArenaStringPtr email_;
  ::google::protobuf::internal::ArenaStringPtr home_address_;
  ::google::protobuf::internal::ArenaStringPtr born_timestamp_;
  ::google::protobuf::internal::ArenaStringPtr idcard_;
  ::google::protobuf::internal::ArenaStringPtr otherid_;
  ::google::protobuf::internal::ArenaStringPtr photo_;
  ::google::protobuf::internal::ArenaStringPtr desc_;
  ::google::protobuf::internal::ArenaStringPtr degree_;
  ::google::protobuf::internal::ArenaStringPtr job_;
  ::google::protobuf::internal::ArenaStringPtr income_;
  ::google::protobuf::internal::ArenaStringPtr marry_;
  ::google::protobuf::internal::ArenaStringPtr hobyy_;
  ::google::protobuf::internal::ArenaStringPtr recommender_;
  ::google::protobuf::internal::ArenaStringPtr belief_;
  ::google::protobuf::internal::ArenaStringPtr idname_;
  ::google::protobuf::int64 sex_;
  ::google::protobuf::int64 wechat_;
  bool approved_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_identity_5fuser_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Identity_User

// string id = 1;
inline void Identity_User::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Identity_User::id() const {
  // @@protoc_insertion_point(field_get:Identity_User.id)
  return id_.GetNoArena();
}
inline void Identity_User::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Identity_User.id)
}
#if LANG_CXX11
inline void Identity_User::set_id(::std::string&& value) {
  
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Identity_User.id)
}
#endif
inline void Identity_User::set_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Identity_User.id)
}
inline void Identity_User::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Identity_User.id)
}
inline ::std::string* Identity_User::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:Identity_User.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Identity_User::release_id() {
  // @@protoc_insertion_point(field_release:Identity_User.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Identity_User::set_allocated_id(::std::string* id) {
  if (id != nullptr) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:Identity_User.id)
}

// string nickname = 2;
inline void Identity_User::clear_nickname() {
  nickname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Identity_User::nickname() const {
  // @@protoc_insertion_point(field_get:Identity_User.nickname)
  return nickname_.GetNoArena();
}
inline void Identity_User::set_nickname(const ::std::string& value) {
  
  nickname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Identity_User.nickname)
}
#if LANG_CXX11
inline void Identity_User::set_nickname(::std::string&& value) {
  
  nickname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Identity_User.nickname)
}
#endif
inline void Identity_User::set_nickname(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  nickname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Identity_User.nickname)
}
inline void Identity_User::set_nickname(const char* value, size_t size) {
  
  nickname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Identity_User.nickname)
}
inline ::std::string* Identity_User::mutable_nickname() {
  
  // @@protoc_insertion_point(field_mutable:Identity_User.nickname)
  return nickname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Identity_User::release_nickname() {
  // @@protoc_insertion_point(field_release:Identity_User.nickname)
  
  return nickname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Identity_User::set_allocated_nickname(::std::string* nickname) {
  if (nickname != nullptr) {
    
  } else {
    
  }
  nickname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), nickname);
  // @@protoc_insertion_point(field_set_allocated:Identity_User.nickname)
}

// string head_hash = 3;
inline void Identity_User::clear_head_hash() {
  head_hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Identity_User::head_hash() const {
  // @@protoc_insertion_point(field_get:Identity_User.head_hash)
  return head_hash_.GetNoArena();
}
inline void Identity_User::set_head_hash(const ::std::string& value) {
  
  head_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Identity_User.head_hash)
}
#if LANG_CXX11
inline void Identity_User::set_head_hash(::std::string&& value) {
  
  head_hash_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Identity_User.head_hash)
}
#endif
inline void Identity_User::set_head_hash(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  head_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Identity_User.head_hash)
}
inline void Identity_User::set_head_hash(const char* value, size_t size) {
  
  head_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Identity_User.head_hash)
}
inline ::std::string* Identity_User::mutable_head_hash() {
  
  // @@protoc_insertion_point(field_mutable:Identity_User.head_hash)
  return head_hash_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Identity_User::release_head_hash() {
  // @@protoc_insertion_point(field_release:Identity_User.head_hash)
  
  return head_hash_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Identity_User::set_allocated_head_hash(::std::string* head_hash) {
  if (head_hash != nullptr) {
    
  } else {
    
  }
  head_hash_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), head_hash);
  // @@protoc_insertion_point(field_set_allocated:Identity_User.head_hash)
}

// string name = 4;
inline void Identity_User::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Identity_User::name() const {
  // @@protoc_insertion_point(field_get:Identity_User.name)
  return name_.GetNoArena();
}
inline void Identity_User::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Identity_User.name)
}
#if LANG_CXX11
inline void Identity_User::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Identity_User.name)
}
#endif
inline void Identity_User::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Identity_User.name)
}
inline void Identity_User::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Identity_User.name)
}
inline ::std::string* Identity_User::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:Identity_User.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Identity_User::release_name() {
  // @@protoc_insertion_point(field_release:Identity_User.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Identity_User::set_allocated_name(::std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:Identity_User.name)
}

// int64 sex = 5;
inline void Identity_User::clear_sex() {
  sex_ = PROTOBUF_LONGLONG(0);
}
inline ::google::protobuf::int64 Identity_User::sex() const {
  // @@protoc_insertion_point(field_get:Identity_User.sex)
  return sex_;
}
inline void Identity_User::set_sex(::google::protobuf::int64 value) {
  
  sex_ = value;
  // @@protoc_insertion_point(field_set:Identity_User.sex)
}

// string phone = 6;
inline void Identity_User::clear_phone() {
  phone_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Identity_User::phone() const {
  // @@protoc_insertion_point(field_get:Identity_User.phone)
  return phone_.GetNoArena();
}
inline void Identity_User::set_phone(const ::std::string& value) {
  
  phone_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Identity_User.phone)
}
#if LANG_CXX11
inline void Identity_User::set_phone(::std::string&& value) {
  
  phone_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Identity_User.phone)
}
#endif
inline void Identity_User::set_phone(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  phone_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Identity_User.phone)
}
inline void Identity_User::set_phone(const char* value, size_t size) {
  
  phone_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Identity_User.phone)
}
inline ::std::string* Identity_User::mutable_phone() {
  
  // @@protoc_insertion_point(field_mutable:Identity_User.phone)
  return phone_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Identity_User::release_phone() {
  // @@protoc_insertion_point(field_release:Identity_User.phone)
  
  return phone_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Identity_User::set_allocated_phone(::std::string* phone) {
  if (phone != nullptr) {
    
  } else {
    
  }
  phone_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), phone);
  // @@protoc_insertion_point(field_set_allocated:Identity_User.phone)
}

// int64 wechat = 7;
inline void Identity_User::clear_wechat() {
  wechat_ = PROTOBUF_LONGLONG(0);
}
inline ::google::protobuf::int64 Identity_User::wechat() const {
  // @@protoc_insertion_point(field_get:Identity_User.wechat)
  return wechat_;
}
inline void Identity_User::set_wechat(::google::protobuf::int64 value) {
  
  wechat_ = value;
  // @@protoc_insertion_point(field_set:Identity_User.wechat)
}

// string email = 8;
inline void Identity_User::clear_email() {
  email_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Identity_User::email() const {
  // @@protoc_insertion_point(field_get:Identity_User.email)
  return email_.GetNoArena();
}
inline void Identity_User::set_email(const ::std::string& value) {
  
  email_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Identity_User.email)
}
#if LANG_CXX11
inline void Identity_User::set_email(::std::string&& value) {
  
  email_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Identity_User.email)
}
#endif
inline void Identity_User::set_email(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  email_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Identity_User.email)
}
inline void Identity_User::set_email(const char* value, size_t size) {
  
  email_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Identity_User.email)
}
inline ::std::string* Identity_User::mutable_email() {
  
  // @@protoc_insertion_point(field_mutable:Identity_User.email)
  return email_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Identity_User::release_email() {
  // @@protoc_insertion_point(field_release:Identity_User.email)
  
  return email_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Identity_User::set_allocated_email(::std::string* email) {
  if (email != nullptr) {
    
  } else {
    
  }
  email_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), email);
  // @@protoc_insertion_point(field_set_allocated:Identity_User.email)
}

// string home_address = 9;
inline void Identity_User::clear_home_address() {
  home_address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Identity_User::home_address() const {
  // @@protoc_insertion_point(field_get:Identity_User.home_address)
  return home_address_.GetNoArena();
}
inline void Identity_User::set_home_address(const ::std::string& value) {
  
  home_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Identity_User.home_address)
}
#if LANG_CXX11
inline void Identity_User::set_home_address(::std::string&& value) {
  
  home_address_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Identity_User.home_address)
}
#endif
inline void Identity_User::set_home_address(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  home_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Identity_User.home_address)
}
inline void Identity_User::set_home_address(const char* value, size_t size) {
  
  home_address_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Identity_User.home_address)
}
inline ::std::string* Identity_User::mutable_home_address() {
  
  // @@protoc_insertion_point(field_mutable:Identity_User.home_address)
  return home_address_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Identity_User::release_home_address() {
  // @@protoc_insertion_point(field_release:Identity_User.home_address)
  
  return home_address_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Identity_User::set_allocated_home_address(::std::string* home_address) {
  if (home_address != nullptr) {
    
  } else {
    
  }
  home_address_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), home_address);
  // @@protoc_insertion_point(field_set_allocated:Identity_User.home_address)
}

// string born_timestamp = 10;
inline void Identity_User::clear_born_timestamp() {
  born_timestamp_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Identity_User::born_timestamp() const {
  // @@protoc_insertion_point(field_get:Identity_User.born_timestamp)
  return born_timestamp_.GetNoArena();
}
inline void Identity_User::set_born_timestamp(const ::std::string& value) {
  
  born_timestamp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Identity_User.born_timestamp)
}
#if LANG_CXX11
inline void Identity_User::set_born_timestamp(::std::string&& value) {
  
  born_timestamp_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Identity_User.born_timestamp)
}
#endif
inline void Identity_User::set_born_timestamp(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  born_timestamp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Identity_User.born_timestamp)
}
inline void Identity_User::set_born_timestamp(const char* value, size_t size) {
  
  born_timestamp_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Identity_User.born_timestamp)
}
inline ::std::string* Identity_User::mutable_born_timestamp() {
  
  // @@protoc_insertion_point(field_mutable:Identity_User.born_timestamp)
  return born_timestamp_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Identity_User::release_born_timestamp() {
  // @@protoc_insertion_point(field_release:Identity_User.born_timestamp)
  
  return born_timestamp_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Identity_User::set_allocated_born_timestamp(::std::string* born_timestamp) {
  if (born_timestamp != nullptr) {
    
  } else {
    
  }
  born_timestamp_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), born_timestamp);
  // @@protoc_insertion_point(field_set_allocated:Identity_User.born_timestamp)
}

// string idcard = 11;
inline void Identity_User::clear_idcard() {
  idcard_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Identity_User::idcard() const {
  // @@protoc_insertion_point(field_get:Identity_User.idcard)
  return idcard_.GetNoArena();
}
inline void Identity_User::set_idcard(const ::std::string& value) {
  
  idcard_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Identity_User.idcard)
}
#if LANG_CXX11
inline void Identity_User::set_idcard(::std::string&& value) {
  
  idcard_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Identity_User.idcard)
}
#endif
inline void Identity_User::set_idcard(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  idcard_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Identity_User.idcard)
}
inline void Identity_User::set_idcard(const char* value, size_t size) {
  
  idcard_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Identity_User.idcard)
}
inline ::std::string* Identity_User::mutable_idcard() {
  
  // @@protoc_insertion_point(field_mutable:Identity_User.idcard)
  return idcard_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Identity_User::release_idcard() {
  // @@protoc_insertion_point(field_release:Identity_User.idcard)
  
  return idcard_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Identity_User::set_allocated_idcard(::std::string* idcard) {
  if (idcard != nullptr) {
    
  } else {
    
  }
  idcard_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), idcard);
  // @@protoc_insertion_point(field_set_allocated:Identity_User.idcard)
}

// string otherid = 12;
inline void Identity_User::clear_otherid() {
  otherid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Identity_User::otherid() const {
  // @@protoc_insertion_point(field_get:Identity_User.otherid)
  return otherid_.GetNoArena();
}
inline void Identity_User::set_otherid(const ::std::string& value) {
  
  otherid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Identity_User.otherid)
}
#if LANG_CXX11
inline void Identity_User::set_otherid(::std::string&& value) {
  
  otherid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Identity_User.otherid)
}
#endif
inline void Identity_User::set_otherid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  otherid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Identity_User.otherid)
}
inline void Identity_User::set_otherid(const char* value, size_t size) {
  
  otherid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Identity_User.otherid)
}
inline ::std::string* Identity_User::mutable_otherid() {
  
  // @@protoc_insertion_point(field_mutable:Identity_User.otherid)
  return otherid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Identity_User::release_otherid() {
  // @@protoc_insertion_point(field_release:Identity_User.otherid)
  
  return otherid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Identity_User::set_allocated_otherid(::std::string* otherid) {
  if (otherid != nullptr) {
    
  } else {
    
  }
  otherid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), otherid);
  // @@protoc_insertion_point(field_set_allocated:Identity_User.otherid)
}

// string photo = 13;
inline void Identity_User::clear_photo() {
  photo_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Identity_User::photo() const {
  // @@protoc_insertion_point(field_get:Identity_User.photo)
  return photo_.GetNoArena();
}
inline void Identity_User::set_photo(const ::std::string& value) {
  
  photo_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Identity_User.photo)
}
#if LANG_CXX11
inline void Identity_User::set_photo(::std::string&& value) {
  
  photo_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Identity_User.photo)
}
#endif
inline void Identity_User::set_photo(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  photo_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Identity_User.photo)
}
inline void Identity_User::set_photo(const char* value, size_t size) {
  
  photo_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Identity_User.photo)
}
inline ::std::string* Identity_User::mutable_photo() {
  
  // @@protoc_insertion_point(field_mutable:Identity_User.photo)
  return photo_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Identity_User::release_photo() {
  // @@protoc_insertion_point(field_release:Identity_User.photo)
  
  return photo_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Identity_User::set_allocated_photo(::std::string* photo) {
  if (photo != nullptr) {
    
  } else {
    
  }
  photo_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), photo);
  // @@protoc_insertion_point(field_set_allocated:Identity_User.photo)
}

// string desc = 14;
inline void Identity_User::clear_desc() {
  desc_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Identity_User::desc() const {
  // @@protoc_insertion_point(field_get:Identity_User.desc)
  return desc_.GetNoArena();
}
inline void Identity_User::set_desc(const ::std::string& value) {
  
  desc_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Identity_User.desc)
}
#if LANG_CXX11
inline void Identity_User::set_desc(::std::string&& value) {
  
  desc_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Identity_User.desc)
}
#endif
inline void Identity_User::set_desc(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  desc_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Identity_User.desc)
}
inline void Identity_User::set_desc(const char* value, size_t size) {
  
  desc_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Identity_User.desc)
}
inline ::std::string* Identity_User::mutable_desc() {
  
  // @@protoc_insertion_point(field_mutable:Identity_User.desc)
  return desc_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Identity_User::release_desc() {
  // @@protoc_insertion_point(field_release:Identity_User.desc)
  
  return desc_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Identity_User::set_allocated_desc(::std::string* desc) {
  if (desc != nullptr) {
    
  } else {
    
  }
  desc_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), desc);
  // @@protoc_insertion_point(field_set_allocated:Identity_User.desc)
}

// string degree = 15;
inline void Identity_User::clear_degree() {
  degree_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Identity_User::degree() const {
  // @@protoc_insertion_point(field_get:Identity_User.degree)
  return degree_.GetNoArena();
}
inline void Identity_User::set_degree(const ::std::string& value) {
  
  degree_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Identity_User.degree)
}
#if LANG_CXX11
inline void Identity_User::set_degree(::std::string&& value) {
  
  degree_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Identity_User.degree)
}
#endif
inline void Identity_User::set_degree(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  degree_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Identity_User.degree)
}
inline void Identity_User::set_degree(const char* value, size_t size) {
  
  degree_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Identity_User.degree)
}
inline ::std::string* Identity_User::mutable_degree() {
  
  // @@protoc_insertion_point(field_mutable:Identity_User.degree)
  return degree_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Identity_User::release_degree() {
  // @@protoc_insertion_point(field_release:Identity_User.degree)
  
  return degree_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Identity_User::set_allocated_degree(::std::string* degree) {
  if (degree != nullptr) {
    
  } else {
    
  }
  degree_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), degree);
  // @@protoc_insertion_point(field_set_allocated:Identity_User.degree)
}

// string job = 16;
inline void Identity_User::clear_job() {
  job_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Identity_User::job() const {
  // @@protoc_insertion_point(field_get:Identity_User.job)
  return job_.GetNoArena();
}
inline void Identity_User::set_job(const ::std::string& value) {
  
  job_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Identity_User.job)
}
#if LANG_CXX11
inline void Identity_User::set_job(::std::string&& value) {
  
  job_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Identity_User.job)
}
#endif
inline void Identity_User::set_job(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  job_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Identity_User.job)
}
inline void Identity_User::set_job(const char* value, size_t size) {
  
  job_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Identity_User.job)
}
inline ::std::string* Identity_User::mutable_job() {
  
  // @@protoc_insertion_point(field_mutable:Identity_User.job)
  return job_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Identity_User::release_job() {
  // @@protoc_insertion_point(field_release:Identity_User.job)
  
  return job_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Identity_User::set_allocated_job(::std::string* job) {
  if (job != nullptr) {
    
  } else {
    
  }
  job_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), job);
  // @@protoc_insertion_point(field_set_allocated:Identity_User.job)
}

// string income = 17;
inline void Identity_User::clear_income() {
  income_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Identity_User::income() const {
  // @@protoc_insertion_point(field_get:Identity_User.income)
  return income_.GetNoArena();
}
inline void Identity_User::set_income(const ::std::string& value) {
  
  income_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Identity_User.income)
}
#if LANG_CXX11
inline void Identity_User::set_income(::std::string&& value) {
  
  income_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Identity_User.income)
}
#endif
inline void Identity_User::set_income(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  income_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Identity_User.income)
}
inline void Identity_User::set_income(const char* value, size_t size) {
  
  income_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Identity_User.income)
}
inline ::std::string* Identity_User::mutable_income() {
  
  // @@protoc_insertion_point(field_mutable:Identity_User.income)
  return income_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Identity_User::release_income() {
  // @@protoc_insertion_point(field_release:Identity_User.income)
  
  return income_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Identity_User::set_allocated_income(::std::string* income) {
  if (income != nullptr) {
    
  } else {
    
  }
  income_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), income);
  // @@protoc_insertion_point(field_set_allocated:Identity_User.income)
}

// string marry = 18;
inline void Identity_User::clear_marry() {
  marry_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Identity_User::marry() const {
  // @@protoc_insertion_point(field_get:Identity_User.marry)
  return marry_.GetNoArena();
}
inline void Identity_User::set_marry(const ::std::string& value) {
  
  marry_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Identity_User.marry)
}
#if LANG_CXX11
inline void Identity_User::set_marry(::std::string&& value) {
  
  marry_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Identity_User.marry)
}
#endif
inline void Identity_User::set_marry(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  marry_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Identity_User.marry)
}
inline void Identity_User::set_marry(const char* value, size_t size) {
  
  marry_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Identity_User.marry)
}
inline ::std::string* Identity_User::mutable_marry() {
  
  // @@protoc_insertion_point(field_mutable:Identity_User.marry)
  return marry_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Identity_User::release_marry() {
  // @@protoc_insertion_point(field_release:Identity_User.marry)
  
  return marry_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Identity_User::set_allocated_marry(::std::string* marry) {
  if (marry != nullptr) {
    
  } else {
    
  }
  marry_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), marry);
  // @@protoc_insertion_point(field_set_allocated:Identity_User.marry)
}

// string hobyy = 19;
inline void Identity_User::clear_hobyy() {
  hobyy_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Identity_User::hobyy() const {
  // @@protoc_insertion_point(field_get:Identity_User.hobyy)
  return hobyy_.GetNoArena();
}
inline void Identity_User::set_hobyy(const ::std::string& value) {
  
  hobyy_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Identity_User.hobyy)
}
#if LANG_CXX11
inline void Identity_User::set_hobyy(::std::string&& value) {
  
  hobyy_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Identity_User.hobyy)
}
#endif
inline void Identity_User::set_hobyy(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  hobyy_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Identity_User.hobyy)
}
inline void Identity_User::set_hobyy(const char* value, size_t size) {
  
  hobyy_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Identity_User.hobyy)
}
inline ::std::string* Identity_User::mutable_hobyy() {
  
  // @@protoc_insertion_point(field_mutable:Identity_User.hobyy)
  return hobyy_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Identity_User::release_hobyy() {
  // @@protoc_insertion_point(field_release:Identity_User.hobyy)
  
  return hobyy_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Identity_User::set_allocated_hobyy(::std::string* hobyy) {
  if (hobyy != nullptr) {
    
  } else {
    
  }
  hobyy_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), hobyy);
  // @@protoc_insertion_point(field_set_allocated:Identity_User.hobyy)
}

// string recommender = 20;
inline void Identity_User::clear_recommender() {
  recommender_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Identity_User::recommender() const {
  // @@protoc_insertion_point(field_get:Identity_User.recommender)
  return recommender_.GetNoArena();
}
inline void Identity_User::set_recommender(const ::std::string& value) {
  
  recommender_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Identity_User.recommender)
}
#if LANG_CXX11
inline void Identity_User::set_recommender(::std::string&& value) {
  
  recommender_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Identity_User.recommender)
}
#endif
inline void Identity_User::set_recommender(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  recommender_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Identity_User.recommender)
}
inline void Identity_User::set_recommender(const char* value, size_t size) {
  
  recommender_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Identity_User.recommender)
}
inline ::std::string* Identity_User::mutable_recommender() {
  
  // @@protoc_insertion_point(field_mutable:Identity_User.recommender)
  return recommender_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Identity_User::release_recommender() {
  // @@protoc_insertion_point(field_release:Identity_User.recommender)
  
  return recommender_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Identity_User::set_allocated_recommender(::std::string* recommender) {
  if (recommender != nullptr) {
    
  } else {
    
  }
  recommender_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), recommender);
  // @@protoc_insertion_point(field_set_allocated:Identity_User.recommender)
}

// string belief = 21;
inline void Identity_User::clear_belief() {
  belief_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Identity_User::belief() const {
  // @@protoc_insertion_point(field_get:Identity_User.belief)
  return belief_.GetNoArena();
}
inline void Identity_User::set_belief(const ::std::string& value) {
  
  belief_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Identity_User.belief)
}
#if LANG_CXX11
inline void Identity_User::set_belief(::std::string&& value) {
  
  belief_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Identity_User.belief)
}
#endif
inline void Identity_User::set_belief(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  belief_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Identity_User.belief)
}
inline void Identity_User::set_belief(const char* value, size_t size) {
  
  belief_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Identity_User.belief)
}
inline ::std::string* Identity_User::mutable_belief() {
  
  // @@protoc_insertion_point(field_mutable:Identity_User.belief)
  return belief_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Identity_User::release_belief() {
  // @@protoc_insertion_point(field_release:Identity_User.belief)
  
  return belief_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Identity_User::set_allocated_belief(::std::string* belief) {
  if (belief != nullptr) {
    
  } else {
    
  }
  belief_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), belief);
  // @@protoc_insertion_point(field_set_allocated:Identity_User.belief)
}

// string idname = 22;
inline void Identity_User::clear_idname() {
  idname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Identity_User::idname() const {
  // @@protoc_insertion_point(field_get:Identity_User.idname)
  return idname_.GetNoArena();
}
inline void Identity_User::set_idname(const ::std::string& value) {
  
  idname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Identity_User.idname)
}
#if LANG_CXX11
inline void Identity_User::set_idname(::std::string&& value) {
  
  idname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Identity_User.idname)
}
#endif
inline void Identity_User::set_idname(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  idname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Identity_User.idname)
}
inline void Identity_User::set_idname(const char* value, size_t size) {
  
  idname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Identity_User.idname)
}
inline ::std::string* Identity_User::mutable_idname() {
  
  // @@protoc_insertion_point(field_mutable:Identity_User.idname)
  return idname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Identity_User::release_idname() {
  // @@protoc_insertion_point(field_release:Identity_User.idname)
  
  return idname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Identity_User::set_allocated_idname(::std::string* idname) {
  if (idname != nullptr) {
    
  } else {
    
  }
  idname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), idname);
  // @@protoc_insertion_point(field_set_allocated:Identity_User.idname)
}

// bool approved = 23;
inline void Identity_User::clear_approved() {
  approved_ = false;
}
inline bool Identity_User::approved() const {
  // @@protoc_insertion_point(field_get:Identity_User.approved)
  return approved_;
}
inline void Identity_User::set_approved(bool value) {
  
  approved_ = value;
  // @@protoc_insertion_point(field_set:Identity_User.approved)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_identity_5fuser_2eproto
